# Generated by Django 4.2.6 on 2024-02-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_description", models.TextField()),
                ("hyperparameters", models.TextField()),
                ("ensemble", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("worst_path", models.CharField(max_length=255)),
                ("error_path", models.CharField(max_length=255)),
                ("mean_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("idx", models.IntegerField()),
                ("path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f1_score", models.FloatField()),
                ("recall", models.FloatField()),
                ("f2_score", models.FloatField()),
                ("balanced_accuracy", models.FloatField()),
                ("confusion_matrix", models.CharField(max_length=255)),
                ("global_features_plot", models.CharField(max_length=255)),
                ("beeswarm_plot", models.CharField(max_length=255)),
                (
                    "classifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classifier_comparison.classifier",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(to="classifier_comparison.feature"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classifier",
            name="benign_instances",
            field=models.ManyToManyField(
                related_name="benign_metrics", to="classifier_comparison.instance"
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="closest_instances",
            field=models.ManyToManyField(
                related_name="closest_metrics", to="classifier_comparison.instance"
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="malignant_instances",
            field=models.ManyToManyField(
                related_name="malignant_metrics", to="classifier_comparison.instance"
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="missclassified_instances",
            field=models.ManyToManyField(
                related_name="missclassified_metrics",
                to="classifier_comparison.instance",
            ),
        ),
    ]
