# Generated by Django 4.2.6 on 2024-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classifier_comparison",
            "0002_remove_metric_name_classifier_hyperparameters_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="beeswarm_plot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="metric",
            name="global_features_plot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="confusion_matrix",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="GlobalShap",
        ),
    ]
