# Generated by Django 4.2.6 on 2024-02-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classifier_comparison",
            "0003_metric_beeswarm_plot_metric_global_features_plot_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("worst_path", models.CharField(max_length=255)),
                ("error_path", models.CharField(max_length=255)),
                ("mean_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="metric",
            name="beeswarm_plot",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="metric",
            name="global_features_plot",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="metric",
            name="features",
            field=models.ManyToManyField(to="classifier_comparison.feature"),
        ),
    ]
